# documentation at: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: 'cargo'
    directory: '/src'
    schedule:
      interval: 'daily'
    # a high limit is useful when dependabot only checks monthly
    open-pull-requests-limit: 30
    # ignore non-security patch updates on all deps
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    target-branch: 'main'
    # don't auto-rebase, otherwise dependabot will rebase several PRs at once
    # and create many hours of unnecessary workflow runs
    rebase-strategy: 'disabled'
    milestone: 24 # "Code health and maintenance"
    labels:
      - 'Component: Build'