[workspace]

members = [
    "main",
    "test",
    "lib/formatting-nostd",
    "lib/gml-parser",
    "lib/linux-api",
    "lib/log-c2rust",
    "lib/logger",
    "lib/pod",
    "lib/shadow-build-common",
    "lib/shadow-shim-helper-rs",
    "lib/shmem",
    "lib/shim",
    "lib/std-util",
    "lib/syscall-logger",
    "lib/tsc",
    "lib/vasi",
    "lib/vasi-macro",
    "lib/vasi-sync",
]
