# Syntax reference:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Lint Checks
permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

env:
  CARGO_TERM_COLOR: always

jobs:

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          # Run on PR head instead of merge result. Running on the merge
          # result can give confusing results, and we require PR to be up to
          # date with target branch before merging, anyway.
          # See https://github.com/shadow/shadow/issues/2166
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install flake8
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude src/external

  lint-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Run on PR head instead of merge result. Running on the merge
          # result can give confusing results, and we require PR to be up to
          # date with target branch before merging, anyway.
          # See https://github.com/shadow/shadow/issues/2166
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Rustfmt check
        run: (cd src && cargo fmt -- --check)

  lint-cargo-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cargo update check
        run: |
          # This will return an error if any versions of local crates in the Cargo.lock
          # are out of date compared to the crate versions in Cargo.toml. This can fail
          # if the Shadow version is bumped without using Cargo to update the lock file.
          (cd src && cargo update --locked --workspace)

  lint-bindings:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    env:
      CONTAINER: ubuntu:22.04
      CC: clang
      CXX: clang++
      RUSTPROFILE: minimal
    steps:
      - name: Install git
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y git
      # Work around https://github.com/actions/checkout/issues/760
      - name: add safe.directory
        run: git config --global --add safe.directory $PWD
      # This must come *after* installing git, so that the checkout action
      # uses git and creates a "real" checkout that we can later `git diff`.
      # Otherwise it uses the GH API to just copy the contents locally, but
      # doesn't create a .git directory.
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          # Run on PR head instead of merge result. Running on the merge
          # result can give confusing results, and we require PR to be up to
          # date with target branch before merging, anyway.
          # See https://github.com/shadow/shadow/issues/2166
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get month
        id: get-month
        run: |
          echo "::set-output name=month::$(/bin/date -u "+%Y%m")"
      - name: Install dependencies
        run: |
          ci/container_scripts/install_deps.sh
          ci/container_scripts/install_extra_deps.sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Restore cargo registry cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          # invalidate the cache once per month
          key: cargo-registry-${{ steps.get-month.outputs.month }}
          restore-keys: |
            cargo-registry-
      - name: Check bindings (release)
        run: |
          (cd src && cargo build --release --features bindings)
          git diff --exit-code
      - name: Check bindings (debug)
        run: |
          (cd src && cargo build --features bindings)
          git diff --exit-code